himanshu007-creator/SFC-foundations

- present_source_code/index.html
- present_source_code/wp-includes/css/dist/block-library/style.min.css
Hey, I am Avinash, a participant of GSSoC'21. 
I have aligned all the 3 projects on the front page of the site. As none of the 3 projects were in line. I have aligned the images and the below descriptive text of projects so that all 3 projects have the same font and styles.
> Aligned the project section in one manner

- .github/label-commenter-config.yml
- .github/workflows/label-commenter.yml
Added Label Commenter bot, please let me know if any changes are required in the comment generated by the bot or anything else.
Fixes #83
> Label commenter bot

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
> ISSUE_TEMPLATE created

- README.md
I have the tech stacks used in this project so that README.MD file will look more attractive.
> Added Tech stacks used

- README.md
Update the readme.md file with some GIFs.
Fixes #7
> Update README.md and added Some GIFs

- index.html
I have made changes in line 17, change the following code.
rel="text/css"
to
rel="stylesheet"
Fixes #137 
* Operating system:WINDOWS
* Version:10
* Text-editors used: VS code
> Fix the relevance attribute #137

- .github/ISSUE_TEMPLATE/custom.md
Fixes #144 
Added Issue template as told 
* Version:
> Added Issue template 

- index.html
- js/script.js
Fixed broken links check deployment here https://rohank2502.github.io/SFC-foundations/
> Follow up PR for PR # 153 ( DARK MODE 

- css/style.css
Added the smooth scrolling behavior 
Fixes #157
> [Gssoc21] Added the smooth scrolling 

- css/style.css
I had fixed the responsiveness of preloader in mobile view
Fixes #160
> [Gssoc'21] Fixed the Responsiveness of Preloader

- css/style.css
- index.html
- js/script.js
- Improved the dark mode button
- Added transition while toggling dark/light mode
Fixes #172  
* Operating system: Windows
* Version: 10 pro
* Text-editors used: VS code
* Browser: Chrome, Firefox, Tor, Edge
https://user-images.githubusercontent.com/32588231/114917367-7ce03d00-9e43-11eb-91c3-894d853b11a5.mp4
@himanshu007-creator 
@SnehaVeerakumar
> improved dark-mode

- README.md
Hello @himanshu007-creator I added no.of forks,issues,pr's,stars and licence,repo size in the readme file i.e., for issue #184  . Please review it and let me know.
Before:
After:
> Added no.of forks,stars,issues,pr's and liscense,reposize in readme file

- css/gyan.css
- index.html
- js/gyan.js
- pages/gyan.html
Fixes #188 
https://rohank2502.github.io/SFC-foundations/pages/gyan.html
https://rohank2502.github.io/SFC-foundations/pages/gyan.html
> Gyan Page added 

- css/vatavaran.css
- index.html
- js/vatavaran.js
- pages/vatavaran.html
Added Page Vatavaran 
Fixes #190 
https://rohank2502.github.io/SFC-foundations/pages/vatavaran.html
https://rohank2502.github.io/SFC-foundations/pages/vatavaran.html
> Add Page Vatavaran

- css/Sampuran.css
- css/gyan.css
- css/vatavaran.css
- pages/gyan.html
Added Darkmode to pages 
Fixes #192 
https://rohank2502.github.io/SFC-foundations/pages/Sampuran.html
https://rohank2502.github.io/SFC-foundations/pages/Sampuran.html
> Added Darkmode to pages 

- css/style.css
- index.html
This is About us section on Home Page 
Fixes #201
> About us Section Redesigned 

- README.md
Added two badges of Python and Django respectively.
Fixes#235
Fixes # (235) 
* Version:
> Included Python and Django badges in tech stack (README) #235

- app/models.py
- app/template/pages/Blog/blog_detail.html
- app/urls.py
- app/views.py
https://user-images.githubusercontent.com/67692721/117875658-0e669180-b2c0-11eb-8cc5-13b0be0e955d.mp4
* Version:
> Added Comment Feature in Backend

- css/News/news.css
- pages/News/news.html
> News Page added ! 

- README.md
> Added links to README.md

- css/About-Us/coreteam.css
- css/KMP/kmp.css
- pages/KMP/kmp.html
Made changes in kmp page and core team page and made those pages responsive !! 
Fixes #278 
* Version:
- [x I have performed a self-review of my own code
- [ x] My changes generate no new warnings
https://rohank2502.github.io/SFC-foundations/
> Coreteam & kmp

- pages/About-Us/coreteam.html
- pages/About-Us/founder.html
- pages/About-Us/knowsfc.html
- pages/About-Us/objectives.html
- pages/About-Us/workingmodel.html
- pages/Blog/blog.html
- pages/Contact-Us/contact.html
- pages/Donate/Donate.html
- pages/Events/events.html
- pages/Join-Us/joinus.html
- pages/KMP/kmp.html
- pages/News/news.html
- pages/Projects/Sampuran.html
- pages/Projects/gyan.html
- pages/Projects/vatavaran.html
- pages/Templates/blog.html
- pages/Templates/event.html
- pages/Templates/news.html
Please have a look at changes made ! @himanshu007-creator 
Fixes #280 
* Version:
- [] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
> Fixed navbar links 

- CONTRIBUTING.md
I have modified the contributing.md file to make it readable and efficient .
Fixes #39
> Updated Contributing .md file

- index.html
Fixes #299 
* Version:
- [] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [ x] Any dependent changes have been merged and published in downstream modules
> Reordered Project in Index page !! 

- pages/Join-Us/joinus.html
Fixes #303 
* Version:
- x] I have added tests that prove my fix is effective or that my feature works
> Removed img from JOin us  page  of intern section 

- css/style.css
> Made the pre loader round in shape

- css/slider-event/slider-event.css
- pages/slider-event/slider-event.html
Fixes #311 
* Version:
- [ x] I have commented my code, particularly in hard-to-understand areas
> event page to slider template updated 

- css/slider-event/slider-event.css
Sorry, I forget these changes !! till I push those you merged !!   @himanshu007-creator
> darkmode for event slider page 

- css/About-Us/coreteam.css
- css/About-Us/founder.css
- css/About-Us/knowsfc.css
- css/About-Us/objectives.css
- css/About-Us/workingmodel.css
- css/Contact-Us/contactus.css
- css/Events/events.css
- css/Join-Us/joinus.css
- css/KMP/kmp.css
- css/News/news.css
- css/Projects/Sampuran.css
- css/Projects/gyan.css
- css/Projects/vatavaran.css
- css/Templates/blog.css
- css/Templates/event.css
- css/Templates/news.css
- css/style.css
Have Fixed the issue of the dark mode bug in all pages mainly on the contact us page it was visible ! 
Fixes #293 
* Version:
-  ] I have made corresponding changes to the documentation
> Fixed the issue of navbar in DarkMode 

- Assets/style.css
- css/About-Us/coreteam.css
- css/About-Us/founder.css
- css/About-Us/knowsfc.css
- css/About-Us/objectives.css
- css/About-Us/workingmodel.css
- css/Blog/blog.css
- css/Contact-Us/contactus.css
- css/Events/events.css
- css/Join-Us/joinus.css
- css/KMP/kmp.css
- css/News/news.css
- css/Projects/Sampuran.css
- css/Projects/gyan.css
- css/Projects/vatavaran.css
- css/Templates/blog.css
- css/Templates/event.css
- css/Templates/news.css
- css/slider-event/slider-event.css
- css/style.css
Modified border-radius, color and background color of Feedus Section 
Fixes #317
* Version:
https://shriya030.github.io/SFC-foundations/
> Modified Feed Us Section

- css/slider-event/slider-event.css
- css/style.css
- index.html
Fixes #315 
* Version:
- [] New and existing unit tests pass locally with my changes
- [x ] Any dependent changes have been merged and published in downstream modules
> Dark Mode Bug fixed in news button 

- Assets/index.html
- index.html
- pages/About-Us/coreteam.html
- pages/About-Us/founder.html
- pages/About-Us/knowsfc.html
- pages/About-Us/objectives.html
- pages/About-Us/workingmodel.html
- pages/Blog/blog.html
- pages/Contact-Us/contact.html
- pages/Events/events.html
- pages/Join-Us/joinus.html
- pages/KMP/kmp.html
- pages/News/news.html
- pages/Projects/Sampuran.html
- pages/Projects/gyan.html
- pages/Projects/vatavaran.html
- pages/Templates/blog.html
- pages/Templates/event.html
- pages/Templates/news.html
- pages/slider-event/slider-event.html
Fixes #321 
* Version:
https://shriya030.github.io/SFC-foundations/
> Changed hamburger menu Icon

- css/KMP/kmp.css
Fixes #305 
* Version:
- [x ] My code follows the style guidelines of this project
> Made changes in KMP pages ! 

- Assets/index.html
> Changed path to load image of Gyan project instead of Sampuran project

- pages/About-Us/coreteam.html
Fixes #332 
* Version:
- [ x] I have added tests that prove my fix is effective or that my feature works
> Made changes in core team main page paragraph

- pages/About-Us/workingmodel.html
> updated the content of working model

- pages/About-Us/objectives.html
Fixes #346 
- [] Bug fix (non-breaking change which fixes an issue)
* Version:
- [ x] I have made corresponding changes to the documentation
- [ x] Any dependent changes have been merged and published in downstream modules
> updated the content of objective page

- pages/About-Us/knowsfc.html
Fixes #344 
- [ x] New feature (non-breaking change which adds functionality)
* Version:
- [] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
> updated the content of know sfc page

- pages/About-Us/founder.html
> updated the bio of founder

- pages/Join-Us/joinus.html
> updated the content of join us page

- pages/Contact-Us/contact.html
> Contact us turns yellow when opened

- pages/Projects/vatavaran.html
Fixes #355 
* Version:
#ATTACH SCREEN-SHOTS
> updated vatavarn page content

- pages/Projects/Sampuran.html
Fixes #354 
* Version:
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
> updated the content of  sampuran page

- pages/Projects/gyan.html
Fixes #352 
* Version:
- [] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
> updated the content of gyan page

- Assets/style.css
- css/About-Us/coreteam.css
- css/About-Us/founder.css
- css/About-Us/knowsfc.css
- css/About-Us/objectives.css
- css/About-Us/workingmodel.css
- css/Blog/blog.css
- css/Contact-Us/contactus.css
- css/Events/events.css
- css/Join-Us/joinus.css
- css/KMP/kmp.css
- css/News/news.css
- css/Projects/Sampuran.css
- css/Projects/gyan.css
- css/Projects/vatavaran.css
- css/Templates/blog.css
- css/Templates/event.css
- css/Templates/news.css
- css/slider-event/slider-event.css
- css/style.css
Fixes #319 
* Version:
https://shriya030.github.io/SFC-foundations/
> Changed HamburgerMenu Background

- pages/About-Us/coreteam.html
- pages/About-Us/founder.html
- pages/About-Us/knowsfc.html
- pages/About-Us/objectives.html
- pages/About-Us/workingmodel.html
- pages/Blog/blog.html
- pages/Contact-Us/contact.html
- pages/Events/events.html
- pages/Join-Us/joinus.html
- pages/KMP/kmp.html
- pages/News/news.html
- pages/Projects/Sampuran.html
- pages/Projects/gyan.html
- pages/Projects/vatavaran.html
- pages/Templates/blog.html
- pages/Templates/event.html
- pages/Templates/news.html
- pages/slider-event/slider-event.html
> removed feed from all pages except index

- css/About-Us/coreteam.css
- css/About-Us/founder.css
- css/About-Us/knowsfc.css
- css/About-Us/objectives.css
- css/About-Us/workingmodel.css
- css/Blog/blog.css
- css/Contact-Us/contactus.css
- css/Events/events.css
- css/Join-Us/joinus.css
- css/KMP/kmp.css
- css/News/news.css
- css/Projects/Sampuran.css
- css/Projects/gyan.css
- css/Projects/vatavaran.css
- css/Templates/blog.css
- css/Templates/event.css
- css/Templates/news.css
- css/slider-event/slider-event.css
- css/style.css
> Hover on btn darkmode

- CODE_OF_CONDUCT.md
Code of conduct modified in explainable way .
Fixes #40
> Modified code of conduct

- css/About-Us/knowsfc.css
- pages/About-Us/knowsfc.html
Fixes #367 
* Version:
- [ \x] My code follows the style guidelines of this project
#ATTACH SCREEN-SHOTS
> fixed footer bug in know more page 

- css/About-Us/knowsfc.css
- pages/About-Us/knowsfc.html
> added hexagon design for web version only 

- css/About-Us/coreteam.css
> Fixed the issue of 3rd person going out of the screen

- css/About-Us/coreteam.css
Fixes #381 
* Version:
- [] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
-x ] My changes generate no new warnings
> fixed btn of core team selction

- css/style.css
> aligned for all three devices

- Assets/style.css
> darkmode in tablet

- css/About-Us/knowsfc.css
> made the manual btn of sider alling know sfc page

- css/style.css
> fixed the nav btn on home page slider

- css/KMP/kmp.css
Fixes #378 
* Version:
- [x  My changes generate no new warnings
- [x  I have added tests that prove my fix is effective or that my feature works
#ATTACH SCREEN-SHOTS
> made tablet version of kmp page

- css/About-Us/coreteam.css
- css/About-Us/knowsfc.css
- css/Blog/blog.css
- css/FEED/feed.css
- css/Join-Us/joinus.css
- css/style.css
- pages/About-Us/knowsfc.html
> mob version

- README.md
I have move the badges to the top and added some badges with the links related to them in the README.md file, after clicking on them the user will be redirected to the related section/web page.
This fixes #408  
Tested and verified manually.
> moved badges to the top and added some more 

- README.md
- Tribute_To_Contributors.html
Added tribute to contributors feature.
Created a new HTML file in the root level of the repo with the name Tribute_To_Contributors.html, and added a link to that in the readme.
> [MASTER] Added tribute to contributors.

- css/FEED/feed.css
Changed the font color of the "FEEDING PAWS" page in dark mode to increase the visibility of the text.
Fixes #424
> Changes made on Feed Page

- pages/Donate/Donate.html
Changed "Futures for childrens" to "Future for Children"
Fixes #427 
* Operating system: Windows
* Version:
* Text-editors used: Vscode
> fixed typo in donate page

- index.html
- pages/FEED/feed.html
I have updated the count of feeding paws from `190` to `3669` in  
[line 1](https://github.com/himanshu007-creator/SFC-foundations/blob/38f805accfaf0e4eff993abf06a3b44482c93bf4/index.html#L57)
[line 2](https://github.com/himanshu007-creator/SFC-foundations/blob/38f805accfaf0e4eff993abf06a3b44482c93bf4/pages/FEED/feed.html#L149)
Fixes #429 
* Operating system: Ubuntu
* Version: 20.04.2 LTS(Focal Fosaa)
* Text-editors used: Visual Studio Code
> Changes done

- css/About-Us/knowsfc.css
- pages/About-Us/knowsfc.html
Added a button to knowsfc.html within a link directed to coreteam.html, added CSS and responsiveness.
Fixes #431 
* Operating system: Windows
* Version: 10
* Text-editors used: VScode
> added coreteam button link

- css/style.css
- index.html
-It will be better if , the flickering live button on home page , will has a fixed position . That will provide better UI experience . As for now , it is scrolling with each slide separately .
Fixes #420  
* Version:
> Home page live button bug fixed
